Complete YouTube homepage clone
rashedarman/youtube-home pull request #1
Opened 2022-11-03 23:05 UTC by rashedarman

- You should use a linter in order to detect syntactic or stylistic errors and suspicious constructs.
- Please follow professional Github flow
- It is recommended that you put proper comments on different sections of markup for better readability.

2022-11-03 23:07 UTC, rashedarman commented on index.html
> +    <div class="header">
You could use HTML header semantic tags here. This makes your code much more readable.

2022-11-03 23:08 UTC, rashedarman commented on index.html
> +    <div class="header">
You could use HTML `header` semantic tags here. This makes your code much more readable.

2022-11-03 23:10 UTC, rashedarman commented on styles.css
> +  margin-bottom: 15px;
You could use the CSS `margin` shorthand property here.

2022-11-04 00:57 UTC, Yerimah requested changes
# Status: Required Changes 🔴 

Hi @rashedarman, 👋  

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f4d634a5755566852566e493378656f516f6d2f67697068792e676966](https://user-images.githubusercontent.com/71140133/199861499-962e86f7-d51c-4194-a761-38fd74aed0b5.gif)

## Highlights
- GitHub flow ✅ 
- PR title descriptive ✅ 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-04 00:57 UTC, Yerimah commented on README.md
> +- [Belay Birhanu Gibina](https://github.com/belaymit)
- [ ] I would encourage you to make sure to add content, listing the technology used in the project and how to run it, to them so your README is more informative and professional. You can use the microverse [README template](https://github.com/microverseinc/readme-template/blob/master/README.md). 
- [ ] As part of the general requirement for this project, make sure to setup linters correctly for this project.

2022-11-04 00:57 UTC, Yerimah commented on index.html
> +      </div>
- [ ] I noticed some of the icons are not clickable. I would kindly suggest you nest the `<I>` tag in an `<a>` anchor tag in order to improve the user experience of your application. 👍

2022-11-04 13:46 UTC, rashedarman commented on index.html
> +        <i class="material-icons">videocam</i>
I noticed some of the icons are not clickable. I would kindly suggest you nest the <I> tag in an <a> anchor tag in order to improve the user experience of your application. +1

2022-11-04 13:48 UTC, rashedarman commented on README.md
> +- [Belay Birhanu Gibina](https://github.com/belaymit)
- [ ] I would encourage you to make sure to add content, listing the technology used in the project and how to run it, to them so your README is more informative and professional. You can use the microverse [README template](https://github.com/microverseinc/readme-template/blob/master/README.md). 
- [ ] As part of the general requirement for this project, make sure to setup linters correctly for this project.

2022-11-04 13:49 UTC, rashedarman commented on README.md
> +- [Belay Birhanu Gibina](https://github.com/belaymit)
- [ ] I would encourage you to make sure to add content, listing the technology used in the project and how to run it, to them so your README is more informative and professional. You can use the microverse [README template](https://github.com/microverseinc/readme-template/blob/master/README.md). 
- [ ] As part of the general requirement for this project, make sure to setup linters correctly for this project.

2022-11-04 14:17 UTC, Favourezeugwa approved these changes
## STATUS: APPROVED 🥇 🍹 🏆 

Hi @rashedarman , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 🎉🎉 

![bunnys](https://user-images.githubusercontent.com/99246359/199996991-730ce005-c435-4b10-b959-86cbb4e8f6bd.gif)


## Highlights 💯 
- Inline comments used ✔️ 
- Stated reasons WHY a change should be implemented ✔️ 
- Left more than two comments ✔️ 

## Optional suggestions

✅  I would like to kindly suggest that you learn how to use GitHub Review features in Approving, Or requesting a change in a PR.

🌸 Here is a link to a video on [how to use GitHub features](https://www.loom.com/share/e847c46aa4814534b23b3a8e4dd60d6d)

✅ Please, I think it is better not to delete comments made by reviewers. This will help the next reviewer track the previous changes that was requested.

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-04 14:18 UTC, Favourezeugwa commented on README.md
> +- [Belay Birhanu Gibina](https://github.com/belaymit)
- Great Job explaining WHY a change needs to be implemented. It sounds polite as well.

[OPTIONAL] 👍🏽 
- I think you can include emojis to your comments to make them sound a bit more friendly. You can as well apply this suggestions to all your comments. 🌸

2022-11-04 14:18 UTC, Favourezeugwa commented on index.html
> +        <i class="material-icons">account_circle</i>
[OPTIONAL] 👍🏽 

- I believe this can be rephrased as (" I think your links are not clickable, could you kindly wrap each of the icons around an `<a>` tag?. An `<a> ` has an href attribute that will help connect each icon to their respective social media page 👍🏽 ").

- What do you think?? 🤗

2022-11-04 17:08 UTC, merged